
server:
  port: 8081
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/microservices
#    username: root
#    password: aA@7030225457 
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    
#    jpa:
#     hibernate:
#      ddl-auto: update
#      show-sql: true
# 
#     
#     

spring:
  application:
    name: USER-SERVICE

  datasource:
    password: aA@7030225457
    url: jdbc:mysql://localhost:3306/microservices
    username: root
  jpa:
    hibernate:
      ddl-auto: update

  config:
    import: configserver:http://localhost:5050


#
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#

management:
  health:
    circuitbreakers:
      enabled: true

  endpoints:
    web:
      exposure:
        include: health

  endpoint:
    health:
      show-details: always

resilience4j:
  circuitBreaker:
    registerHealthIndicator: true
    eventConsumerBufferSize: 10
    failureRateThreshold: 50
    minimumNumberOfCalls: 5
    automaticTransitionFromOpenToHalfOpenEnabled: true
    waitDurationInOpenState: 6s
    permittedNumberOfCallsInHalfOpenState: 3
    slidingWindowSize: 10
    slidingWindowType: COUNT_BASED

ratelimiter:
  instances:
    userRateLimiter:
      limit-refresh-period: 4s
      limit-for-period: 2
      timeout-duration: 2s





